services:
  db:
    image: postgres:latest
    ports:
      - 5432:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - tripdb:/var/lib/postgresql/data
    networks:
      - db-network
  app:
    build: .
    command: ["sh", "-c", "npm install && npm run start"]
    ports:
      - 8080:8080
    volumes:
      - .:/usr/app
    environment:
      - TRIP_DATABASE_URL=${TRIP_DATABASE_URL}
    depends_on:
      - db
    networks:
      - db-network

volumes:
  tripdb:

networks:
  db-network:
    driver: bridge